import logger from '../../utils/logger'; //Refer to the logger.js file in the utils folder
export default function handler(req, res) {
  logger.info('This log was generated by Winston and collected by the New Relic Node.js APM agent.');

  res.status(200).json({ message: 'Log sent to New Relic successfully.' });
}
