import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const sendLog = async () => {
    const response = await fetch('/api/winstonexample');
    const data = await response.json();
    console.log(data); // This is just for demonstration
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Apply Flexbox styling directly to main to center the button */}
      <main style={{ 
        display: 'flex', 
        justifyContent: 'center', 
        alignItems: 'center', 
        height: '100vh', 
        flexDirection: 'column' // Stack vertically
      }}>
        <button onClick={sendLog} style={{ padding: '10px 20px', fontSize: '16px' }}>
          Click me to send log to New Relic
        </button>
      </main>
    </>
  );
}
